### ISSUE TITLE
_process_error() cleanup

### ISSUE THREAD

**Issue by pricemi115** [pricemi115/grumptech-spawn-helper#5]
Once the error is converted to a buffer, invoke _process_stderror_data() for succinctnes

**Comment by prakha** [comment]
i am interested in solving the issue.

**Comment by pricemi115** [comment]
@prakha - Go for it! Fork the repo and put up a pull request. It is not "really" a per-se. It was more of a note to myself to clean up the code since in `_process_error()` after the line `        // Convert the string to a Buffer, to be compatible with the error data member.
        const errBuf = _buffer.from(errData, 'utf-8');`, the remainder of the function is identical to  `_process_stderror_data()`
